Traceback (most recent call last):
  File "foodcnn.py", line 3, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
Traceback (most recent call last):
  File "foodcnn.py", line 3, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
Traceback (most recent call last):
  File "foodcnn.py", line 1, in <module>
    import pandas as pd
  File "/home/jchang2/.local/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['dateutil']
